"""Add birthday_date column to birth_photo

Revision ID: 10dcac1662f0
Revises: d47eacb9ea0d
Create Date: 2025-06-25 05:18:04.114671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10dcac1662f0'
down_revision = 'd47eacb9ea0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birth_photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday_date', sa.String(length=10), nullable=False))
        batch_op.alter_column('birthday_year',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birth_photo', schema=None) as batch_op:
        batch_op.alter_column('birthday_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('birthday_date')

    # ### end Alembic commands ###
