"""Add BirthPhoto table

Revision ID: ae292bb26fac
Revises: 10dcac1662f0
Create Date: 2025-06-25 05:31:57.030988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae292bb26fac'
down_revision = '10dcac1662f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birth_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('birthday_year', sa.Integer(), nullable=False),
    sa.Column('birthday_date', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birth_photo')
    # ### end Alembic commands ###
